### ISSUE TITLE
Please add example for kicad_animation

### ISSUE THREAD

**Issue by JakubAndrysek** [linalinn/kicad-render#4]
```yaml
name: pcb_image
on:
  push:
jobs:
  render-image:
    name: render-image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: render pcb image
        uses: linalinn/kicad-render@main
        with:
        pcb_file: <path from repo root to .kicad_pcb>
        output_path: ${{ github.workspace }}/images
        animation: gif
...
```

Last line `animation: gif` or `animation: mp4`

Thanks
